### ISSUE TITLE
The Pitch

### ISSUE THREAD

**Issue by nvanbaak** [dyoder838/CityScoop#10]

**Comment by dyoder838** [comment]
Cityscoop
The dynamic city information search
this includes the basics that you get from a cities page, but, brings the information you want, to you, in one search i.e. cuts down your research time. 

saves searches to compare cities


Weather trends
Average COL
	- jobs available v. income 
Population
	- kid friendliness rating
	- neighborhood ratings  
Growing Job Markets
Current trends
Politics
	- red or blue
	- candidate info
	- current leadership 
		○ policies
	- Religion
	- Covid status
	- hot topics
	- social movments 
police 
health 
school
